title: Predictability in Microbiology
description: Short posts on predictability in microbiology
theme: minima

plugins:
  - jekyll-titles-from-headings

titles_from_headings:
  enabled: true
  strip_title: true
  collections: true


# Only these pages will show as header links:
header_pages:
  - index.md           # optional
``
  
